# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# You can find the latest versions here: https://projects.neoforged.net/neoforged/neoforge
minecraft_version=1.26.1
minecraft_version_range=[1.26.1,)
# The Neo version must agree with the Minecraft version to get a valid artifact
neo_version=26.1.2.75
# The Neo version range can use any version of Neo as bounds
neo_version_range=[26,)
# The loader version range can only use the major version of FML as bounds
loader_version_range=[4,)
mod_id=seeloewen_itemdumper
mod_name=Seeloewen ItemDumper
mod_license=GNU GPL 3.0
mod_version=1.0.0-Beta1
mod_group_id=me.seeloewen
mod_authors=Seeloewen
mod_description=Dumps a list of all registered item ids to a file
